CREATE TABLE PERSON
(
	PERSON_ID NUMBER(19) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
);

CREATE TABLE ADDRESS
(
	ADDRESS_ID NUMBER(19) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	PROVINCE VARCHAR(50) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
);
